services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    volumes:
      - ./config:/config/rclone
      - ./data:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command: >
      mount alist:. /data/alist
      --use-mmap 
      --no-checksum 
      --no-modtime 
      --umask 0022 
      --vfs-cache-mode full 
      --vfs-cache-max-age 3h 
      --vfs-cache-min-free-space 3G 
      --vfs-read-chunk-size 32M 
      --vfs-read-chunk-size-limit 256M

networks:
  default:
    name: nas-net
    external: true