services:
  rclone:
    image: rclone/rclone
    volumes:
      - ./config:/config/rclone
      - ./data:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command: >
      mount alist: /data/alist 
      -vv
      --use-mmap 
      --no-checksum 
      --no-modtime 
      --umask 0022 
      --vfs-cache-mode minimal 
      --vfs-read-chunk-streams 0 
      --vfs-read-chunk-size 16M 
      --vfs-read-chunk-size-limit 512M
    privileged: true
    restart: unless-stopped
networks:
  default:
    name: nas-net
    external: true