services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CFD_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '0.25'
