services:
  jellyfin:
    image: nyanmisaka/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: ./media
        target: /media
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.uemind.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'