services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest-rockchip
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ../media
        target: /media
    restart: unless-stopped
    group_add:
      - 107
      - 44
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.uemind.com
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
    name: my-net
    external: true