services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest-rockchip
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ../media
        target: /media
    restart: unless-stopped
    privileged: true
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.uemind.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'