services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ../media
        target: /media
        read_only: true
    restart: unless-stopped
    group_add:
      - "993"
      - "video"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.uemind.com
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
    name: my-net
    external: true