services:
  alist:
    image: xhofe/alist-aria2:latest
    container_name: alist
    volumes:
      - ./data:/opt/alist/data
      - type: bind
        source: ../media
        target: /media
    ports:
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
networks:
  default:
    name: my-net